# This is the configuration used to check the rubocop source code.

inherit_from: vendor/bundler/ruby/2.1.0/gems/rubocop-0.20.1/rubocop-todo.yml

AllCops:
  RunRailsCops: true

MethodLength:
  Max: 22

ClassLength:
  Max: 140

CyclomaticComplexity:
  Max: 12

AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

HashSyntax:
  EnforcedStyle: ruby19

LineLength:
  Max: 150

ParameterLists:
  Max: 5
  CountKeywordArgs: true

AsciiComments:
  Enabled: false

AndOr:
  Enabled: false

ClassLength:
  Enabled: false

# FavorSprintf:
#   Enabled: false

Documentation:
  Enabled: false
